name: mask_rcnn_tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - ipykernel
  - pip:
    - tensorflow==2.6.1
    - keras==2.6.0
    - numpy==1.19.5
    - pandas==1.3.4
    - scikit-image==0.18.3
    - scikit-learn==1.0.1
    - seaborn==0.11.2
    - ipython==7.29.0
    - imgaug==0.4.0